#!/system/bin/sh
# Gov-Tuner Changelogs
# Copyright (C) 2016 Debuffer and Senthil360 @ XDA-Developers
#	   With help from Paget96 and F4uzan
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#
busybox="/system/etc/GovTuner/busybox"
ver="3.9.1"
divider="==============================================="
$busybox echo "CHANGELOG FOR $ver"
$busybox echo "----------------------"
$busybox echo ""
$busybox echo "Added Cluster support universally for all Android devices  (cannot give 100% assurance as we don't own all the devices)"
$busybox echo "Reworked UI"
$busybox echo "Added option to change governor from Main menu"
$busybox echo "Added option to enable/disable power efficient workqueues"
$busybox echo "New Dynamic method for assigning target load frequencies , now the frequencies specified will not be out of range for your device"
$busybox echo "New Dynamic method for assigning hispeed_freq and go_hispeed_load"
$busybox echo "Interactive totally , major update, Values updated for all Profiles "
$busybox echo ""
$busybox echo "New optimizations for Zzmoove governor"
$busybox echo "Fixed error of profiles not showing up on some devices"
$busybox echo ""
$busybox echo -n "b. Back to menu: "
read -r character
case $character in
b|B)$busybox clear;
sh /system/bin/govtuner;;
esac
